Add --quiet and --quiet-version (-qV) and fix some stderr handlers

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -39,6 +39,11 @@ shift
 done
 }
 
+QUIET=0
+be_quiet() {
+	QUIET=1
+}
+
 VPATH=`dirname ${0}`
 if [ "${VPATH}" = "." ]; then
 	WODIS=current
@@ -120,6 +125,7 @@ Defaults for the options are specified in brackets.
 Configuration:
   -h, --help              display this help and exit
   -r, --report            show what libs/programs require to work
+  -q, --quiet             be less verbose
   -V, --version           display version information and exit
 
 Installation directories:
@@ -159,7 +165,22 @@ take_environ() {
 : ${PREFIX:=/usr/local/}
 }
 
+ochof() {
+	[ "$QUIET" = 1 ] && return
+	printf "$*"
+}
+
+ocho() {
+	[ "$QUIET" = 1 ] && return
+	echo "$*"
+}
+
 show_version() {
+<<<<<<< HEAD
+if [ "$QUIET" = 1 ]; then
+	echo "1.9.3"
+	exit 0
+fi
 echo "acr-1.9.3 configuration script done with acr v1.9.3.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
@@ -180,6 +201,11 @@ fi
 case $flag in
 -h|--help|--hel|--h|--he|-help)
 	show_usage ; ;;
+-qV|-quiet-version|--quiet-version)
+	be_quiet
+	show_version ; ;;
+-q|-quiet|--quiet)
+	be_quiet ; ;;
 -V|-version|--version)
 	show_version ; ;;
 -r|--r|--report)
@@ -251,18 +277,18 @@ ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCD
 
 create_environ
 
-echo "checking build system type... ${BUILD}"
-echo "checking host system type... ${HOST}"
-echo "checking target system type... ${TARGET}"
+ocho "checking build system type... ${BUILD}"
+ocho "checking host system type... ${HOST}"
+ocho "checking target system type... ${TARGET}"
 [ "${CROSSBUILD}" = 1 ] && echo "using crosscompilation mode."
 
 #split_host BUILD HOST TARGET
 [ -n "${prefix}" ] && PREFIX="${prefix}"
-echo "checking for working directories... ${WODIS}"
-echo "using prefix '${PREFIX}'"
+ocho "checking for working directories... ${WODIS}"
+ocho "using prefix '${PREFIX}'"
 ACR_RMFILES=""
 
-printf "checking for install... "
+ochof "checking for install... "
 if [ -x "${INSTALL}" ]; then
 	FIND=${INSTALL}
 else
@@ -277,13 +303,17 @@ else
 	unset IFS
 fi
 if [ -n "${FIND}" ]; then
-	echo ${FIND};
+	ocho ${FIND};
 HAVE_INSTALL=1
 	INSTALL=${FIND}
 else
 	HAVE_INSTALL=0
 	INSTALL=install
-echo no ; fi
+if [ "" = 1 ]; then
+echo "Cannot find install" >&2
+else
+echo no
+fi ; fi
 SEDFLAGS=" -e '"
 COUNT=0
 for A in ${ENVWORDS} ; do
@@ -308,7 +338,7 @@ if [ -f "${VPATH}/${A}.acr" ]; then
    exit 1
   fi
  fi
- echo "creating ${SD_TARGET}"
+ ocho "creating ${SD_TARGET}"
 mkdir -p $(echo ${A} | sed -e "s,/`basename ${A}`$,,g")
  cat ${VPATH}/${SD_TARGET}.acr | \
 eval sed -e "s,@VPATH@,${VPATH}/${A},g" ${SEDFLAGS} > ${SD_TARGET}.tmp
@@ -327,13 +357,15 @@ done
  if [ ! $? = 0 ]; then echo Cannot write target file ; control_c ; fi
 done
 
+if [ "$QUIET" = 0 ]; then
 echo
 echo "Final report:"
-for A in  SPREFIX PREFIX INSTALL VERSION CONTACT ; do # REPORT
+for A in  SPREFIX PREFIX INSTALL VERSION CONTACT ; do
 eval VAL="\$${A}"
 [ -z "${VAL}" ] && VAL="(null)"
 echo " - ${A} = ${VAL}"
 done
+fi
 #ACR# (( package information ))
 #ACR# PKGNAME acr
 #ACR# VERSION 1.9.3
diff --git a/src/acr-sh b/src/acr-sh
--- a/src/acr-sh
+++ b/src/acr-sh
@@ -324,7 +324,7 @@ check_prg() {
 # XXX: -x check is also valid for directories
 	SCRIPT=`cat <<EOF
 ${SCRIPT}
-printf "checking for ${_CHKPRG_NAME}... "
+ochof "checking for ${_CHKPRG_NAME}... "
 if [ -x "${S}{${_CHKPRG_VAR}}" ]; then
 	FIND=${S}{${_CHKPRG_VAR}}
 else
@@ -339,13 +339,17 @@ else
 	unset IFS
 fi
 if [ -n "${S}{FIND}" ]; then
-	echo ${S}{FIND};
+	ocho ${S}{FIND};
 HAVE_${_CHKPRG_VAR}=1
 	${_CHKPRG_VAR}=${S}{FIND}
 else
 	HAVE_${_CHKPRG_VAR}=0
 	${_CHKPRG_VAR}=${_CHKPRG_NAME}
+if [ "$QUIET" = 1 ]; then
+echo "Cannot find ${_CHKPRG_NAME}" >&2
+else
 echo no
+fi
 EOF
 `
 	if [ "${_CHKPRG_REQUIRED}" = 1 ]; then
@@ -1403,8 +1407,8 @@ _EOF_
 ## {{{ Generate Output file
 report_h() {
 	echo "for A in ${H_FILES}; do"
-	echo " echo \"creating h ${S}{VPATH}/${S}{A}\""
-	echo "  echo '' > ${S}{VPATH}/${S}{A}"
+	echo " ocho \"creating h ${S}{VPATH}/${S}{A}\""
+	echo "  ocho '' > ${S}{VPATH}/${S}{A}"
 	echo "if [ ! \$? = 0 ]; then echo Cannot write target file ; control_c ; fi"
 	echo " for B in ${S}{ENVWORDS} ; do"
 	echo "  eval \"VAR=\\${S}${S}{B}\""
@@ -1430,9 +1434,9 @@ report_h() {
 
 report_sh() {
 	echo "for A in ${SH_FILES}; do # SH_FILES"
-	echo " echo \"creating sh ${S}{VPATH}/${S}{A}\""
+	echo " ocho \"creating sh ${S}{VPATH}/${S}{A}\""
 	echo "  echo '# automatically generated by acr' > ${S}{VPATH}/${S}{A}"
-	echo "if [ ! \$? = 0 ]; then echo Cannot write target file ; control_c ; fi"
+	echo "if [ ! \$? = 0 ]; then echo Cannot write target file >&2 ; control_c ; fi"
 	echo " for B in ${S}{ENVWORDS} ; do"
 	echo "  eval \"VAR=\\${S}${S}{B}\""
 	echo "  echo ${S}{B}=${S}{VAR} >> ${S}{VPATH}/${S}{A}"
@@ -1510,7 +1514,7 @@ if [ -f "${S}{VPATH}/${S}{A}.acr" ]; then
    exit 1
   fi
  fi
- echo "creating ${S}{SD_TARGET}"
+ ocho "creating ${S}{SD_TARGET}"
 mkdir -p \$(echo ${S}{A} | sed -e "s,/\`basename ${S}{A}\`\$,,g")
  cat ${S}{VPATH}/${S}{SD_TARGET}.acr | \\
 eval sed -e "s,@VPATH@,${S}{VPATH}/${S}{A},g" ${S}{SEDFLAGS} > ${S}{SD_TARGET}.tmp
@@ -1557,6 +1561,11 @@ eval "${S}1_OS=\"${S}SPLIT_OS\""
 shift
 [ -z "${S}1" ] && break
 done
+}
+
+QUIET=0
+be_quiet() {
+	QUIET=1
 }
 
 VPATH=\`dirname ${S}{0}\`
@@ -1641,6 +1650,7 @@ Defaults for the options are specified in brackets.
 Configuration:
   -h, --help              display this help and exit
   -r, --report            show what libs/programs require to work
+  -q, --quiet             be less verbose
   -V, --version           display version information and exit
 
 Installation directories:
@@ -1720,7 +1730,21 @@ cat <<EOF
 : ${S}{PREFIX:=/usr/local/}
 }
 
+ochof() {
+	[ "${S}QUIET" = 1 ] && return
+	printf "${S}*"
+}
+
+ocho() {
+	[ "${S}QUIET" = 1 ] && return
+	echo "${S}*"
+}
+
 show_version() {
+if [ "${S}QUIET" = 1 ]; then
+	echo "${VERSION}"
+	exit 0
+fi
 echo "${PKGNAME}-${VERSION} configuration script done with acr v${ACR_VERSION}.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
@@ -1741,6 +1765,11 @@ fi
 case \$flag in
 -h|--help|--hel|--h|--he|-help)
 	show_usage ; ;;
+-qV|-quiet-version|--quiet-version)
+	be_quiet
+	show_version ; ;;
+-q|-quiet|--quiet)
+	be_quiet ; ;;
 -V|-version|--version)
 	show_version ; ;;
 -r|--r|--report)
@@ -1839,17 +1868,17 @@ check_path() {
 	[ "${SPLIT}" = 1 ] && return
 	cat <<EOF
 [ -n "${S}{prefix}" ] && PREFIX="${S}{prefix}"
-echo "checking for working directories... ${S}{WODIS}"
-echo "using prefix '${S}{PREFIX}'"
+ocho "checking for working directories... ${S}{WODIS}"
+ocho "using prefix '${S}{PREFIX}'"
 EOF
 }
 
 check_os() {
 	[ "${STRIP}" = 1 ] && return
 	cat <<EOF
-echo "checking build system type... ${S}{BUILD}"
-echo "checking host system type... ${S}{HOST}"
-echo "checking target system type... ${S}{TARGET}"
+ocho "checking build system type... ${S}{BUILD}"
+ocho "checking host system type... ${S}{HOST}"
+ocho "checking target system type... ${S}{TARGET}"
 [ "${S}{CROSSBUILD}" = 1 ] && echo "using crosscompilation mode."
 
 #split_host BUILD HOST TARGET
@@ -1910,7 +1939,7 @@ if [ -x ${S}{A}/configure ]; then
 	./configure ${S}@
 	cd - > /dev/null
 else
-	echo "Cannot find ./configure on directory ${S}{A}."
+	echo "Cannot find ./configure on directory ${S}{A}." >&2
 	exit 1
 fi
 done
@@ -1921,13 +1950,15 @@ EOF
 show_report() {
 	[ "${REPORT}" ] &&\
 	cat <<EOF
+if [ "${S}QUIET" = 0 ]; then
 echo
 echo "Final report:"
-for A in ${REPORT} ; do # REPORT
+for A in ${REPORT} ; do
 eval VAL="\\${S}${S}{A}"
 [ -z "${S}{VAL}" ] && VAL="(null)"
 echo " - ${S}{A} = ${S}{VAL}"
 done
+fi
 EOF
 }
 # }}}
