Support pkgconf as an alternative to pkg-config

diff --git a/src/acr-sh b/src/acr-sh
--- a/src/acr-sh
+++ b/src/acr-sh
@@ -2807,9 +2807,9 @@ ${STR} ; fi"
 			add_envword ${TMP_VAR}
 			# TODO: Use EOF or F="$F B"
 			REPORT_PKGCFG="${REPORT_PKGCFG} ${STR}"
-			SCRIPT="`printf \"${SCRIPT}\n[ -z \\\"${S}{PKGCONFIG}\\\" ] && PKGCONFIG=pkg-config\"`"
+			SCRIPT="`printf \"${SCRIPT}\nif [ -z \\\"${S}{PKGCONFIG}\\\" ]; then pkg-config --version >/dev/null 2>&1 ; if [ $? = 0 ]; then PKGCONFIG=pkg-config ; else PKGCONFIG=pkgconf ; fi; fi\"`"
 			if [ -z "${ONCE_PKGCONFIG}" ]; then
-				SCRIPT="`printf \"${SCRIPT}\ntype ${S}{PKGCONFIG} > /dev/null 2>&1 || echo \\\"ERROR: Cannot find PKGCONFIG ${S}{PKGCONFIG}\\\"\"`"
+				SCRIPT="`printf \"${SCRIPT}\ntype ${S}{PKGCONFIG} > /dev/null 2>&1 || echo \\\"ERROR: Cannot find valid PKGCONFIG, pkg-config or pkgconf in PATH\\\"\"`"
 				SCRIPT="`printf \"${SCRIPT}\necho 'Using PKGCONFIG: '${S}{PKGCONFIG}\"`"
 				ONCE_PKGCONFIG=1
 			fi
