Don't use /dev/stderr

diff --git a/src/acr-cat b/src/acr-cat
--- a/src/acr-cat
+++ b/src/acr-cat
@@ -47,18 +47,18 @@ if [ -z "$1" ]; then
 fi
 
 if [ ! -f "$1" ]; then
-	echo "error: target file '$1' does not exist." > /dev/stderr
+	echo "error: target file '$1' does not exist." >&2
 	exit 1
 fi
 
 if [ ! -x "$1" ]; then
-	echo "error: target file '$1' is not executable." > /dev/stderr
+	echo "error: target file '$1' is not executable." >&2
 	exit 1
 fi
 
 VERSION="`./${1} --version 2>/dev/null`"
 if [ -z "`echo ${VERSION} | grep ACR`" ]; then
-	echo "error: this is not an acr generated configure script." > /dev/stderr
+	echo "error: this is not an acr generated configure script." >&2
 	exit 1
 fi
 
diff --git a/src/amr b/src/amr
--- a/src/amr
+++ b/src/amr
@@ -114,7 +114,7 @@ check_cidep() {
 		[ "$A" = "$FILE" ] && return
 	done
 
-	echo "CInclude ${FILE} not found" > /dev/stderr
+	echo "CInclude ${FILE} not found" >&2
 	exit 1
 }
 
@@ -124,7 +124,7 @@ check_cdep() {
 		[ "$A" = "$FILE" ] && return
 	done
 
-	echo "CSource ${FILE} not found" > /dev/stderr
+	echo "CSource ${FILE} not found" >&2
 	exit 1
 }
 
@@ -212,7 +212,7 @@ fi
 
 parse_configure_amr() {
 FILE=$1
-echo "Parsing ${FILE}..." >/dev/stderr
+echo "Parsing ${FILE}..." >&2
 CONFIGURE_AMR="`cat ${FILE} 2>/dev/null`"
 for A in $CONFIGURE_AMR ; do
 	# TODO: Support for oneline commands and /* */
@@ -268,7 +268,7 @@ for A in $CONFIGURE_AMR ; do
 			eval "${CDEPS_VAR}=\"\$${CDEPS_VAR} ${A}\""
 			;;
 		*|0)
-			echo "Invalid keyword '$A'" > /dev/stderr
+			echo "Invalid keyword '$A'" >&2
 			exit 1
 			;;
 		esac
