* Bump to 0.9 * Fix $? = 1 checks

diff --git a/src/acr-sh b/src/acr-sh
--- a/src/acr-sh
+++ b/src/acr-sh
@@ -1069,7 +1069,7 @@ PTHREAD_LIBS=-lpthread ; fi
 echo '#include <pthread.h>' > test.c
 echo 'main(){pthread_testcancel();}' >> test.c
 eval \\\\${S}${S}{COMPILER} ${S}{PTHREAD_LIBS} test.c 2>&1 >/dev/null
-if [ \$? = 1 ]; then
+if [ ! \$? = 0 ]; then
 HAVE_PTHREAD=0 ; echo no ; else HAVE_PTHREAD=1; echo yes ; fi
 "
 	if [ "${_REQUIRED}" = 1 ]; then
@@ -1221,7 +1221,7 @@ report_h() {
 	echo "for A in ${H_FILES}; do"
 	echo " echo \"creating h ${S}{VPATH}/${S}{A}\""
 	echo "  echo '' > ${S}{VPATH}/${S}{A}"
-	echo "if [ \$? = 1 ]; then echo Cannot write target file ; control_c ; fi"
+	echo "if [ ! \$? = 0 ]; then echo Cannot write target file ; control_c ; fi"
 	echo " for B in ${S}{ENVWORDS} ; do"
 	echo "  eval \"VAR=\\${S}${S}{B}\""
 	if [ "${_REPORT_DEFINED}" = 1 ]; then
@@ -1248,7 +1248,7 @@ report_sh() {
 	echo "for A in ${SH_FILES}; do # SH_FILES"
 	echo " echo \"creating sh ${S}{VPATH}/${S}{A}\""
 	echo "  echo '# automatically generated by acr' > ${S}{VPATH}/${S}{A}"
-	echo "if [ \$? = 1 ]; then echo Cannot write target file ; control_c ; fi"
+	echo "if [ ! \$? = 0 ]; then echo Cannot write target file ; control_c ; fi"
 	echo " for B in ${S}{ENVWORDS} ; do"
 	echo "  eval \"VAR=\\${S}${S}{B}\""
 	echo "  echo ${S}{B}=${S}{VAR} >> ${S}{VPATH}/${S}{A}"
@@ -1271,7 +1271,7 @@ subst_tags() {
 	echo " for A in ${S_FILES} ; do"
 	echo " echo \"filtering ${S}{A}\""
 	echo "  cat ${S}{VPATH}/${S}{A} | eval sed ${S}{SEDFLAGS} > ${S}{A}"
-	echo "if [ \$? = 1 ]; then echo Cannot write target file ; control_c ; fi"
+	echo "if [ ! \$? = 0 ]; then echo Cannot write target file ; control_c ; fi"
 	echo " done"
 	echo "else #--"
 	# move files
@@ -1297,10 +1297,10 @@ subst_tags() {
 	echo "  fi"
 	echo " fi"
 	echo " cat ${S}{VPATH}/${S}{A}.orig | eval sed ${S}{SEDFLAGS} > ${S}{VPATH}/${S}{A}"
-	echo "if [ \$? = 1 ]; then echo Cannot write target file ; control_c ; fi"
+	echo "if [ ! \$? = 0 ]; then echo Cannot write target file ; control_c ; fi"
 	if [ "${USE_BACKUP}" = 1 ]; then
 		echo " cp ${S}{VPATH}/${S}{A} ${S}{VPATH}/${S}{A}.backup"
-		echo "if [ \$? = 1 ]; then echo Cannot write target file ; control_c ; fi"
+		echo "if [ ! \$? = 0 ]; then echo Cannot write target file ; control_c ; fi"
 	fi
 	echo "done"
 	echo "fi"
@@ -1344,7 +1344,7 @@ if [ -n \"\`grep \\\"${S}{MARK}\\\" ${S}{SD_TARGET}.tmp\`\" ]; then
 fi
 done
  mv ${S}{SD_TARGET}.tmp ${S}{SD_TARGET} && rm -f ${S}{SD_TARGET}.tmp2
- if [ \$? = 1 ]; then echo Cannot write target file ; control_c ; fi
+ if [ ! \$? = 0 ]; then echo Cannot write target file ; control_c ; fi
 done
 "
 }
@@ -2506,7 +2506,7 @@ ${STR} ; fi"
 			SCRIPT="`printf \"${SCRIPT}\nprintf 'checking pkg-config flags for ${STR}... '\"`"
 			## - flags - ##
 			SCRIPT="`printf \"${SCRIPT}\ntmp=\\\`pkg-config --cflags ${STR} 2>/dev/null\\\`\"`"
-			SCRIPT="`printf \"${SCRIPT}\nif [ ${S}? = 1 ]; then echo no ; ${TMP_VAR}=0; \"`"
+			SCRIPT="`printf \"${SCRIPT}\nif [ '!' ${S}? = 0 ]; then echo no ; ${TMP_VAR}=0; \"`"
 			if [ "${_REQUIRED}" = 1 ]; then
 			SCRIPT="`printf \"${SCRIPT}\necho 'This package is required'\nexit 1\"`"
 			fi
@@ -2518,7 +2518,7 @@ ${STR} ; fi"
 			fi
 			## - libs - ##
 			SCRIPT="`printf \"${SCRIPT}\ntmp=\\\`pkg-config --libs ${STR} 2>/dev/null\\\`\"`"
-			SCRIPT="`printf \"${SCRIPT}\nif [ ! ${S}? = 1 ]; then \"`"
+			SCRIPT="`printf \"${SCRIPT}\nif [ ${S}? = 0 ]; then \"`"
 			SCRIPT="`printf \"${SCRIPT}\necho yes; ${TMP_VAR}=1; \";`"
 			if [ "${_PKGCONFIG_PLUS}" = 1 ]; then
 			SCRIPT="`printf \"${SCRIPT}\n${_PC_LDFLAGS}=\\\"${S}${_PC_LDFLAGS} ${S}tmp\\\"; fi; fi\"`"
