Add support for Vala

diff --git a/src/acr-sh b/src/acr-sh
--- a/src/acr-sh
+++ b/src/acr-sh
@@ -101,6 +101,7 @@ C="\`"
 LANG=0           # No langs yet defined
 LANG_C=""        LANG_C_REQUIRED=""      LANG_C_ENV=""    LANG_CPP_ENV=""
 LANC_CXX=""      LANG_CXX_REQUIRED=""    LANG_CXX_ENV=""
+LANG_VALA=""     LANG_VALA_REQUIRED=""   LANG_VALA_ENV=""
 LANG_TCL=""      LANG_TCL_REQUIRED=""    LANG_TCL_ENV=""
 LANG_PERL=""     LANG_PERL_REQUIRED=""   LANG_PERL_ENV=""
 LANG_JAVA=""     LANG_JAVA_REQUIRED=""   LANG_JAVA_ENV=""
@@ -342,27 +343,23 @@ EOF
 	_CHKPRG_NAME=""
 }
 ## }}}
-## {{{ Java
-lang_java() {
+## {{{ Vala
+lang_vala() {
 	SCRIPT=`cat <<_EOF_
 ${SCRIPT}
-printf "checking java compiler... "
-HAVA_LANG_JAVA=1
-echo "class test{public static void main(){}}" > test.java
-if [ "${S}{JAVAC}" = "javac" ]; then if [ "${S}{JAVA_HOME}" ]; then
-	JAVAC="${S}{JAVA_HOME}/bin/javac"
-fi;fi
-${S}{JAVAC} test.java 2>&1 >/dev/null
-if [ ${S}? = 0 ]; then echo ${S}{JAVAC}; else
-	echo no ; HAVE_LANG_JAVA=0
+printf "checking vala compiler... "
+HAVA_LANG_VALA=1
+echo "void main(){}" > test.vala
+${S}{VALAC} test.vala 2>&1 >/dev/null
+if [ ${S}? = 0 ]; then echo ${S}{VALAC}; else
+	echo no ; HAVE_LANG_VALA=0
 _EOF_
 `
-	if [ "${LANG_JAVA_REQUIRED}" = 1 ]; then
+	if [ "${LANG_VALA_REQUIRED}" = 1 ]; then
 SCRIPT="
 ${SCRIPT}
-echo \"ERROR: ${S}{JAVAC} cannot create bytecode\"; exit 1"
+echo \"ERROR: ${S}{VALAC} cannot create C code\"; exit 1"
 	fi
-
 	SCRIPT="${SCRIPT} ; fi"
 }
 env_java() {
@@ -408,6 +405,47 @@ else
 fi
 EOF
 `
+}
+## }}}
+## {{{ Java
+lang_java() {
+	SCRIPT=`cat <<_EOF_
+${SCRIPT}
+printf "checking java compiler... "
+HAVA_LANG_JAVA=1
+echo "class test{public static void main(){}}" > test.java
+if [ "${S}{JAVAC}" = "javac" ]; then if [ "${S}{JAVA_HOME}" ]; then
+	JAVAC="${S}{JAVA_HOME}/bin/javac"
+fi;fi
+${S}{JAVAC} test.java 2>&1 >/dev/null
+if [ ${S}? = 0 ]; then echo ${S}{JAVAC}; else
+	echo no ; HAVE_LANG_JAVA=0
+_EOF_
+`
+	if [ "${LANG_JAVA_REQUIRED}" = 1 ]; then
+SCRIPT="
+${SCRIPT}
+echo \"ERROR: ${S}{JAVAC} cannot create bytecode\"; exit 1"
+	fi
+
+	SCRIPT="${SCRIPT} ; fi"
+}
+env_vala() {
+	[ -n "${LANG_JAVA_ENV}" ] && return
+	LANG=1
+	LANG_VALA=1
+	LANG_VALA_ENV="VALA VALAC HAVE_LANG_VALA"
+	ACR_RMFILES="${ACR_RMFILES} test.vala test"
+	add_lang_envwords "VALA"
+	REPORT_LANGS="${REPORT_LANGS} vala"
+	ENVHELP=`cat <<EOF
+${ENVHELP}
+  VALAC       Vala compiler to be used.
+EOF
+`
+	add_flag with VALAC valac "valac"  "Manually assign the valac program"
+
+	lang_vala
 }
 ## }}}
 ## {{{ Flag parsing (--enable-xxx)
@@ -1502,6 +1540,9 @@ if [ "${LANG_CXX}" = 1 ]; then
 fi
 if [ "${LANG_JAVA}" = 1 ]; then
 	echo ": ${S}{JAVAC:=javac}"
+fi
+if [ "${LANG_VALA}" = 1 ]; then
+	echo ": ${S}{VALAC:=valac}"
 fi
 if [ "${LANG_PERL}" = 1 ]; then
 	echo ": ${S}{PERL:=perl}"
@@ -2833,6 +2874,8 @@ else"
 	"LANG_PYTHON!")         LANG_PYTHON_REQUIRED=1 ; env_python ; ;;
 	"LANG_JAVA")            env_java ; ;;
 	"LANG_JAVA!")           LANG_JAVA_REQUIRED=1 ; env_java ; ;;
+	"LANG_VALA")            env_vala ; ;;
+	"LANG_VALA!")           LANG_VALA_REQUIRED=1 ; env_vala ; ;;
 	"LANG_LUA")             env_lua ; ;;
 	"LANG_LUA!")            LANG_LUA_REQUIRED=1 ; env_lua ; ;;
 	"LANG_PERL")            env_perl ; ;;
